-- Create Medical_Insights table
CREATE TABLE IF NOT EXISTS public."Medical_Insights" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  url TEXT NULL,
  title TEXT NULL,
  abstract TEXT NULL,
  date_posted TEXT NULL,
  field TEXT NULL,
  image_url TEXT NULL,
  CONSTRAINT Medical_Insights_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Create appointments table
CREATE TABLE IF NOT EXISTS public.appointments (
  id UUID NOT NULL,
  doctor_id UUID NOT NULL,
  patient_name TEXT NULL,
  start_time TIMESTAMP WITH TIME ZONE NOT NULL,
  end_time TIMESTAMP WITH TIME ZONE NULL,
  created_at TIMESTAMP WITH TIME ZONE NULL DEFAULT NOW(),
  reminder_sent BOOLEAN NULL DEFAULT FALSE,
  CONSTRAINT appointments_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Create clinical_documents table (without trigger)
CREATE TABLE IF NOT EXISTS public.clinical_documents (
  document_id TEXT NOT NULL,
  patient_id TEXT NOT NULL,
  doctor_id TEXT NOT NULL,
  patient_name TEXT NULL,
  "patient_Sex" TEXT NULL,
  "Birth_date" TEXT NULL,
  patient_address TEXT NULL,
  patient_contact TEXT NULL,
  doctor_name TEXT NULL,
  "Local_Facility_Code" TEXT NULL,
  "Local_Facility_Adress" TEXT NULL,
  "Local_Facility_contact" TEXT NULL,
  document_type TEXT NOT NULL DEFAULT 'Consultation Note',
  document_title TEXT NULL,
  created_at TIMESTAMP WITH TIME ZONE NULL DEFAULT NOW(),
  status TEXT NULL DEFAULT 'draft',
  confidentiality TEXT NULL DEFAULT 'normal',
  "Transcribed_Session" JSONB NOT NULL,
  "TypeDocument" TEXT NULL DEFAULT 'Fichier CDA',
  "Confidentiality_level" TEXT NULL,
  confidentiality_code INTEGER NULL,
  "PastMedicalHistory" TEXT NULL,
  "FamilyHistory" TEXT NULL,
  "SocialHistory" TEXT NULL,
  "Allergies" TEXT NULL,
  "Temperature" TEXT NULL,
  "Weight" TEXT NULL,
  "Height" TEXT NULL,
  "BMI" TEXT NULL,
  "LaboratoryResults" TEXT NULL,
  "DiagnosticImagingReports" TEXT NULL,
  "ProblemList" TEXT NULL,
  "HistoryOfProcedures" TEXT NULL,
  "Medications" TEXT NULL,
  "O2_Saturation" TEXT NULL,
  "CardiacFrequency" TEXT NULL,
  "Goals" TEXT NULL,
  "CarePlan" TEXT NULL,
  "TherapeuticDevices" TEXT NULL,
  "Immunizations" TEXT NULL,
  "PlannedProcedures" TEXT NULL,
  "Assessment" TEXT NULL,
  "PathologyReports" TEXT NULL,
  "NeurologicalSystem" TEXT NULL,
  "DigestiveSystem" TEXT NULL,
  "RespiratorySystem" TEXT NULL,
  "CardiovascularSystem" TEXT NULL,
  "EncounterSummary" TEXT NULL,
  "HistoryOfPresentIllness" TEXT NULL,
  "ReasonForVisit" TEXT NULL,
  "Specialization" TEXT NULL,
  "ArterialPressure" TEXT NULL,
  "Local_Facility_Name" TEXT NULL,
  document_data TEXT NULL,
  source TEXT NULL DEFAULT 'generated',
  CONSTRAINT clinical_documents_pkey PRIMARY KEY (document_id),
  CONSTRAINT clinical_documents_status_check CHECK (
    (status = ANY (ARRAY['draft', 'final', 'amended']))
  )
) TABLESPACE pg_default;

-- Create doctors table
CREATE TABLE IF NOT EXISTS public.doctors (
  doctor_id TEXT NOT NULL,
  full_name TEXT NOT NULL,
  "Specialization" TEXT NULL,
  phone TEXT NULL,
  email TEXT NULL,
  created_at TIMESTAMP WITH TIME ZONE NULL DEFAULT NOW(),
  "License Number" TEXT NULL,
  "Local Facility Code" TEXT NULL,
  "Local Facility Name" TEXT NULL,
  "Local Facility Adress" TEXT NULL,
  password TEXT NULL,
  CONSTRAINT doctors_pkey PRIMARY KEY (doctor_id),
  CONSTRAINT doctors_doctor_id_key UNIQUE (doctor_id)
) TABLESPACE pg_default;

-- Create summary table
CREATE TABLE IF NOT EXISTS public.summary (
  summary_id UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),
  patient_id TEXT NULL,
  summary TEXT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  doctor_id TEXT NULL,
  CONSTRAINT summary_pkey PRIMARY KEY (summary_id)
) TABLESPACE pg_default;

-- Create patients table
CREATE TABLE IF NOT EXISTS public.patients (
  patient_id TEXT NOT NULL,
  full_name TEXT NULL,
  gender TEXT NULL,
  birth_date TEXT NULL,
  address TEXT NULL,
  phone TEXT NULL,
  primary_doctor TEXT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  email TEXT NULL,
  CONSTRAINT patients_pkey PRIMARY KEY (patient_id)
) TABLESPACE pg_default;

-- Create upload table
CREATE TABLE IF NOT EXISTS public.upload (
  summary_id UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),
  patient_id TEXT NULL,
  summary TEXT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  doctor_id TEXT NULL,
  CONSTRAINT upload_pkey PRIMARY KEY (summary_id)
) TABLESPACE pg_default;

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_doctors_id ON public.doctors USING BTREE (doctor_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_doctors_full_name_lower ON public.doctors USING BTREE (LOWER(TRIM(BOTH FROM full_name))) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_doctors_facility_code ON public.doctors USING BTREE (TRIM(BOTH FROM "Local Facility Code")) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_patients_full_name_lower ON public.patients USING BTREE (LOWER(TRIM(BOTH FROM full_name))) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_patients_phone ON public.patients USING BTREE (TRIM(BOTH FROM phone)) TABLESPACE pg_default;